pipeline {

    agent any

    tools {
        maven 'Maven-3.8'
        jdk 'JDK-21'
    }

    environment {
        APP_NAME = "maheflix"
        SERVER_IP = "54.200.67.45"
        REPO_DIR = "maheflix-jenkins"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Check Java and Maven') {
            steps {
                sh '''
                    echo "JAVA_HOME=$JAVA_HOME"
                    java -version
                    javac -version
                    mvn -version
                '''
            }
        }

        stage('Build and Deploy') {
            steps {
                sh """
                ssh -o StrictHostKeyChecking=no ubuntu@${SERVER_IP} '
                    set -e

                    rm -rf ${REPO_DIR}

                    git clone https://github.com/nallam-mahendra/${REPO_DIR}.git

                    cd ${REPO_DIR}/${APP_NAME}

                    java -version
                    mvn -version

                    mvn clean package

                    sudo cp target/${APP_NAME}.war /opt/tomcat/webapps/

                    echo "Deployment completed successfully!"
                '
                """
            }
        }
    }
}
