pipeline {

    agent any

    tools {
        maven 'Maven-3.8'
        jdk 'JDK-21'
    }

    environment {
        APP_NAME = "maheflix"
        SERVER_IP = "35.87.12.190"
        REPO_DIR = "maheflix-jenkins"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build and Deploy') {
            steps {
                sh """
                    ssh -o StrictHostKeyChecking=no ubuntu@${SERVER_IP} "bash -s" <<'REMOTE_SCRIPT'

                    set -e

                    echo "Cleaning previous deployment..."
                    rm -rf ${REPO_DIR}

                    echo "Cloning repository..."
                    git clone https://github.com/nallam-mahendra/${REPO_DIR}.git

                    echo "Moving to application directory..."
                    cd ${REPO_DIR}/${APP_NAME}

                    echo "Setting Java 21..."

                    export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
                    export PATH=/usr/lib/jvm/java-21-openjdk-amd64/bin:/usr/bin:/bin

                    echo "===== JAVA VERSION ====="
                    java -version

                    echo "===== MAVEN VERSION ====="
                    mvn -version

                    echo "===== BUILDING APPLICATION ====="
                    mvn clean package

                    echo "===== CHECKING WAR FILE ====="
                    ls -lh target/

                    echo "===== DEPLOYING WAR ====="

                    sudo cp target/maheflix-webapp.war /opt/tomcat/webapps/maheflix.war

                    echo "===== WAR DEPLOYED ====="

                    echo "===== RESTARTING TOMCAT ====="

                    sudo systemctl restart tomcat

                    echo "===== TOMCAT STATUS ====="

                    sudo systemctl status tomcat --no-pager

                    echo "===== DEPLOYMENT SUCCESSFUL ====="

REMOTE_SCRIPT
                """
            }
        }
    }
}
